name: Deploy Flask App to Vercel

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls the latest code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install necessary packages

      - name: Install Vercel CLI
        run: npm install -g vercel  # Install Vercel CLI

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ fg13NKm7XrsBLFi8y2fsQqFO }}  # Deploy the app
